---
- name: TEST2
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Verifica visibilità /opt/awx-share
    command: ls -l /mnt/awx_share/
    register: result
  
  - debug:
      var: result.stdout_lines
      
  #- name: Pause for 5 minutes to verify mounts
  #  ansible.builtin.pause:
  #    minutes: 5
