---
- name: TEST2
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Trova i file in /mnt/awx_share
    ansible.builtin.find:
      paths: /mnt/awx_share
      file_type: file
    register: found_files

  - name: Mostra i file trovati
    ansible.builtin.debug:
      msg: "{{ item.path }}"
    loop: "{{ found_files.files }}"
