---
- name: TEST2
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Verifica visibilità /tmp
    command: ls -l /tmp
    register: result
  
  - debug:
      var: result.stdout_lines

  - name: Trova i file in /opt/awx_share
    ansible.builtin.find:
      paths: /opt/awx_share
      file_type: file
    register: found_files

  - name: Mostra i file trovati
    ansible.builtin.debug:
      msg: "{{ item.path }}"
    loop: "{{ found_files.files }}"
