---
- name: TEST2
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Verifica visibilità /opt/awx-share
    command: ls -l /mnt/awx_share/
    register: result
  
  - debug:
      var: result.stdout_lines
      
  - name: Scrive un file nella share /mnt/awx_share
    copy:
      dest: /mnt/awx_share/test_awx_output.txt
      content: "Ciao! Questo file è stato scritto da un job AWX dentro l'EE."

  
      
  #- name: Pause for 5 minutes to verify mounts
  #  ansible.builtin.pause:
  #    minutes: 5
